### PR TITLE
Added index.d.ts

### PR DESCRIPTION
**Pull request by sregg**
Added index.d.ts for Typescript types definition

### CODE REVIEW

**Comment by uioporqwerty** [comment]
@zhengjingt Can you merge this please?

**Comment by uioporqwerty** [comment]
@nlt2390 @amin3mej @EmilScherdin Can someone with write access merge and release these changes?

**Comment by amin3mej** [comment]
Hi @uioporqwerty,
I don't have access to merge this PR on this repo.

**Comment by nlt2390** [comment]
@uioporqwerty  @amin3mej  done. sry completely forgot to check this pr.

**Pull request merged**
